-- Generated by Oracle SQL Developer Data Modeler 3.1.0.700
--   at:        2013-11-26 16:39:02 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE App_User CASCADE CONSTRAINTS 
;
DROP TABLE Constr_worker_crew_assign CASCADE CONSTRAINTS 
;
DROP TABLE Construction_project CASCADE CONSTRAINTS 
;
DROP TABLE Construction_worker CASCADE CONSTRAINTS 
;
DROP TABLE Contract CASCADE CONSTRAINTS 
;
DROP TABLE Crew CASCADE CONSTRAINTS 
;
DROP TABLE Crew_project_assignment CASCADE CONSTRAINTS 
;
DROP TABLE Customer CASCADE CONSTRAINTS 
;
DROP TABLE Customer_contract_assign CASCADE CONSTRAINTS 
;
DROP TABLE Disclosure_form CASCADE CONSTRAINTS 
;
DROP TABLE Elevation_code_table CASCADE CONSTRAINTS 
;
DROP TABLE Employee CASCADE CONSTRAINTS 
;
DROP TABLE Floor CASCADE CONSTRAINTS 
;
DROP TABLE House CASCADE CONSTRAINTS 
;
DROP TABLE House_style CASCADE CONSTRAINTS 
;
DROP TABLE Lot CASCADE CONSTRAINTS 
;
DROP TABLE Option_code_table CASCADE CONSTRAINTS 
;
DROP TABLE Option_for_stage CASCADE CONSTRAINTS 
;
DROP TABLE Room CASCADE CONSTRAINTS 
;
DROP TABLE Room_assignment CASCADE CONSTRAINTS 
;
DROP TABLE Sale CASCADE CONSTRAINTS 
;
DROP TABLE Sales_agent CASCADE CONSTRAINTS 
;
DROP TABLE Sales_agent_assignment CASCADE CONSTRAINTS 
;
DROP TABLE School CASCADE CONSTRAINTS 
;
DROP TABLE School_district CASCADE CONSTRAINTS 
;
DROP TABLE Stage_assignment CASCADE CONSTRAINTS 
;
DROP TABLE Stage_code_table CASCADE CONSTRAINTS 
;
DROP TABLE Stage_selected_option CASCADE CONSTRAINTS 
;
DROP TABLE Style_code_table CASCADE CONSTRAINTS 
;
DROP TABLE Style_elevation CASCADE CONSTRAINTS 
;
DROP TABLE Subdivision CASCADE CONSTRAINTS 
;
DROP TABLE Subdivision_agreement CASCADE CONSTRAINTS 
;
DROP TABLE Subdivision_style_option CASCADE CONSTRAINTS 
;
DROP TABLE Task CASCADE CONSTRAINTS 
;
DROP TABLE Task_update CASCADE CONSTRAINTS 
;
CREATE TABLE App_User 
    ( 
     app_user_id NUMBER  NOT NULL , 
     user_type VARCHAR2 (25)  NOT NULL , 
     username VARCHAR2 (25)  NOT NULL , 
     password VARCHAR2 (16)  NOT NULL , 
     password_recovery_question VARCHAR2 (50)  NOT NULL , 
     password_recovery_answer VARCHAR2 (50)  NOT NULL , 
     email VARCHAR2 (25)  NOT NULL CHECK ( email LIKE '%@%') , 
     is_active CHAR (1) DEFAULT 'Y'  NOT NULL 
    ) 
;



ALTER TABLE App_User 
    ADD CONSTRAINT User_PK PRIMARY KEY ( app_user_id ) ;



CREATE TABLE Constr_worker_crew_assign 
    ( 
     constr_worker_crew_assign_id NUMBER  NOT NULL , 
     crew_id NUMBER  NOT NULL , 
     construction_worker_id NUMBER  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE 
    ) 
;



ALTER TABLE Constr_worker_crew_assign 
    ADD CONSTRAINT Constr_worker_crew_assign_PK PRIMARY KEY ( constr_worker_crew_assign_id ) ;



CREATE TABLE Construction_project 
    ( 
     construction_project_id NUMBER  NOT NULL , 
     state_date DATE  NOT NULL , 
     estimated_completion_date DATE  NOT NULL , 
     end_date DATE , 
     project_manager_id NUMBER  NOT NULL , 
     house_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Construction_project 
    ADD CONSTRAINT Construction_project_PK PRIMARY KEY ( construction_project_id ) ;



CREATE TABLE Construction_worker 
    ( 
     construction_worker_id NUMBER  NOT NULL , 
     skills VARCHAR2 (250) , 
     employee_id NUMBER 
    ) 
;



ALTER TABLE Construction_worker 
    ADD CONSTRAINT Construction_worker_PK PRIMARY KEY ( construction_worker_id ) ;



CREATE TABLE Contract 
    ( 
     contract_id NUMBER  NOT NULL , 
     disclosure_form_id NUMBER  NOT NULL , 
     subdivision_agreement_id NUMBER  NOT NULL , 
     date_submitted DATE , 
     time_limit_date DATE  NOT NULL , 
     scanned_image BLOB , 
     is_terminated CHAR (1) DEFAULT 'N' 
    ) 
;



ALTER TABLE Contract 
    ADD CONSTRAINT Contract_PK PRIMARY KEY ( contract_id ) ;



CREATE TABLE Crew 
    ( 
     crew_id NUMBER  NOT NULL , 
     manager_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Crew 
    ADD CONSTRAINT Crew_PK PRIMARY KEY ( crew_id ) ;



CREATE TABLE Crew_project_assignment 
    ( 
     crew_project_assignment_id NUMBER  NOT NULL , 
     crew_id NUMBER  NOT NULL , 
     construction_project_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Crew_project_assignment 
    ADD CONSTRAINT Crew_project_assignment_PK PRIMARY KEY ( crew_project_assignment_id ) ;



CREATE TABLE Customer 
    ( 
     customer_id NUMBER  NOT NULL , 
     app_user_id NUMBER , 
     mortgage_info VARCHAR2 (250) , 
     first_name VARCHAR2 (25)  NOT NULL , 
     last_name VARCHAR2 (25)  NOT NULL , 
     phone_number VARCHAR2 (14)  NOT NULL 
    ) 
;



ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( customer_id ) ;



CREATE TABLE Customer_contract_assign 
    ( 
     customer_contract_assign_id NUMBER  NOT NULL , 
     customer_id NUMBER , 
     contract_id NUMBER 
    ) 
;



ALTER TABLE Customer_contract_assign 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( customer_contract_assign_id ) ;



CREATE TABLE Disclosure_form 
    ( 
     disclosure_form_id NUMBER  NOT NULL , 
     description VARCHAR2 (250)  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE 
    ) 
;



ALTER TABLE Disclosure_form 
    ADD CONSTRAINT Disclosure_form_PK PRIMARY KEY ( disclosure_form_id ) ;



CREATE TABLE Elevation_code_table 
    ( 
     elevation_id NUMBER  NOT NULL , 
     name VARCHAR2 (1)  NOT NULL CHECK ( name IN ('A', 'B', 'C')) , 
     description VARCHAR2 (250) , 
     additional_cost NUMBER (9,2)  NOT NULL 
    ) 
;



ALTER TABLE Elevation_code_table 
    ADD CONSTRAINT Elevation_code_table_PK PRIMARY KEY ( elevation_id ) ;



CREATE TABLE Employee 
    ( 
     employee_id NUMBER  NOT NULL , 
     app_user_id NUMBER , 
     first_name VARCHAR2 (25)  NOT NULL , 
     last_name VARCHAR2 (25)  NOT NULL , 
     home_phone_number VARCHAR2 (14)  NOT NULL , 
     work_phone_number VARCHAR2 (14) , 
     cell_phone_number VARCHAR2 (14) , 
     street_address VARCHAR2 (40)  NOT NULL , 
     city VARCHAR2 (25)  NOT NULL , 
     state VARCHAR2 (2) CHECK ( state IN ('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY')) , 
     zip_code VARCHAR2 (10)  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE 
    ) 
;



ALTER TABLE Employee 
    ADD CONSTRAINT Employee_PK PRIMARY KEY ( employee_id ) ;



CREATE TABLE Floor 
    ( 
     floor_id NUMBER  NOT NULL ,
     floor_description VARCHAR2 (25); 
     house_id NUMBER 
    ) 
;



ALTER TABLE Floor 
    ADD CONSTRAINT Floor_PK PRIMARY KEY ( floor_id ) ;



CREATE TABLE House 
    ( 
     house_id NUMBER  NOT NULL , 
     house_style_id NUMBER , 
     lot_id NUMBER  NOT NULL , 
     escrow_amount NUMBER (8,2) , 
     is_reversed CHAR (1) DEFAULT 'N' , 
     financing_info VARCHAR2 (250) 
    ) 
;



ALTER TABLE House 
    ADD CONSTRAINT House_PK PRIMARY KEY ( house_id ) ;



CREATE TABLE House_style 
    ( 
     house_style_id NUMBER  NOT NULL , 
     reversed_style_id NUMBER 
    ) 
;



ALTER TABLE House_style 
    ADD CONSTRAINT House_style_PK PRIMARY KEY ( house_style_id ) ;



CREATE TABLE Lot 
    ( 
     lot_id NUMBER  NOT NULL , 
     subdivision_id NUMBER  NOT NULL , 
     style_elevation_id NUMBER , 
     latitude NUMBER , 
     longitude NUMBER , 
     street_address VARCHAR2 (40)  NOT NULL , 
     "size" VARCHAR2 (250) , 
     premium NUMBER (9,2)  NOT NULL 
    ) 
;



ALTER TABLE Lot 
    ADD CONSTRAINT Lot_PK PRIMARY KEY ( lot_id ) ;



CREATE TABLE Option_code_table 
    ( 
     option_id NUMBER  NOT NULL , 
     last_possible_stage NUMBER  NOT NULL , 
     option_category VARCHAR2 (25)  NOT NULL CHECK ( option_category IN ('decoration', 'electrical', 'exterior', 'interior', 'plumbing')), 
     description VARCHAR2 (250) 
    ) 
;


ALTER TABLE Option_code_table 
    ADD CONSTRAINT Option_code_table_PK PRIMARY KEY ( option_id ) ;



CREATE TABLE Option_for_stage 
    ( 
     option_for_stage_id NUMBER  NOT NULL , 
     option_id NUMBER  NOT NULL , 
     stage_id NUMBER  NOT NULL , 
     price NUMBER (9,2)  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE 
    ) 
;



ALTER TABLE Option_for_stage 
    ADD CONSTRAINT Option_for_stage_PK PRIMARY KEY ( option_for_stage_id ) ;



CREATE TABLE Room 
    ( 
     room_id NUMBER  NOT NULL , 
     room_type VARCHAR2 (25)  NOT NULL CHECK ( room_type IN ('Attic', 'Basement', 'Bath Room', 'Bed Room', 'Den', 'Dining Room', 'Foyer', 'Garage', 'Hall', 'Kitchen', 'Laundry Room', 'Living Room', 'Mud Room', 'Office', 'Study', 'Work Room')) , 
     description VARCHAR2 (250) , 
     ceiling_type VARCHAR2 (15) CHECK ( ceiling_type IN ('standard', 'tall cathedral', 'vaulted')) 
    ) 
;


ALTER TABLE Room 
    ADD CONSTRAINT Room_PK PRIMARY KEY ( room_id ) ;



CREATE TABLE Room_assignment 
    ( 
     room_assignment_id NUMBER  NOT NULL , 
     room_id NUMBER  NOT NULL , 
     floor_id NUMBER  NOT NULL , 
     "size" VARCHAR2 (250) , 
     num_windows NUMBER (2) CHECK ( num_windows BETWEEN 0 AND 99) 
    ) 
;

ALTER TABLE Room_assignment 
    ADD CONSTRAINT Room_assignment_PK PRIMARY KEY ( room_assignment_id ) ;



CREATE TABLE Sale 
    ( 
     sale_id NUMBER  NOT NULL , 
     escrow_paid CHAR (1) DEFAULT 'N'  NOT NULL , 
     financing_option VARCHAR2 (15) DEFAULT 'unknown'  NOT NULL CHECK ( financing_option IN ('cash', 'mortgage', 'unknown')) , 
     sales_agent_id NUMBER  NOT NULL , 
     house_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Sale 
    ADD CONSTRAINT Sale_PK PRIMARY KEY ( sale_id ) ;



CREATE TABLE Sales_agent 
    ( 
     sales_agent_id NUMBER  NOT NULL , 
     employee_id NUMBER , 
     title VARCHAR2 (250)  NOT NULL , 
     license_num VARCHAR2 (15)  NOT NULL 
    ) 
;



ALTER TABLE Sales_agent 
    ADD CONSTRAINT Sales_agent_PK PRIMARY KEY ( sales_agent_id ) ;



CREATE TABLE Sales_agent_assignment 
    ( 
     sales_agent_assignment_id NUMBER  NOT NULL , 
     house_id NUMBER  NOT NULL , 
     sales_agent_id NUMBER  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE , 
     is_main_sales_agent CHAR (1) DEFAULT 'N'  NOT NULL 
    ) 
;



ALTER TABLE Sales_agent_assignment 
    ADD CONSTRAINT Sales_agent_assignment_PK PRIMARY KEY ( sales_agent_assignment_id ) ;



CREATE TABLE School 
    ( 
     school_id NUMBER  NOT NULL , 
     school_district_id NUMBER  NOT NULL , 
     name VARCHAR2 (25)  NOT NULL 
    ) 
;



ALTER TABLE School 
    ADD CONSTRAINT School_PK PRIMARY KEY ( school_id ) ;



CREATE TABLE School_district 
    ( 
     school_district_id NUMBER  NOT NULL , 
     name VARCHAR2 (25)  NOT NULL 
    ) 
;



ALTER TABLE School_district 
    ADD CONSTRAINT School_district_PK PRIMARY KEY ( school_district_id ) ;



CREATE TABLE Stage_assignment 
    ( 
     stage_assignment_id NUMBER  NOT NULL , 
     construction_project_id NUMBER  NOT NULL , 
     stage_id NUMBER  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE 
    ) 
;



ALTER TABLE Stage_assignment 
    ADD CONSTRAINT Stage_assignment_PK PRIMARY KEY ( stage_assignment_id ) ;



CREATE TABLE Stage_code_table 
    ( 
     stage_id NUMBER  NOT NULL , 
     stage_number NUMBER  NOT NULL CHECK ( stage_number <= 7) , 
     description VARCHAR2 (250) 
    ) 
;



ALTER TABLE Stage_code_table 
    ADD CONSTRAINT Stage_code_table_PK PRIMARY KEY ( stage_id ) ;



CREATE TABLE Stage_selected_option 
    ( 
     stage_selected_option_id NUMBER  NOT NULL , 
     option_for_stage_id NUMBER  NOT NULL , 
     room_assignment_id NUMBER , 
     construction_project_id NUMBER  NOT NULL , 
     date_selected DATE  NOT NULL 
    ) 
;



ALTER TABLE Stage_selected_option 
    ADD CONSTRAINT Stage_selected_option_PK PRIMARY KEY ( stage_selected_option_id ) ;



CREATE TABLE Style_code_table 
    ( 
     style_id NUMBER  NOT NULL , 
     name VARCHAR2 (25)  NOT NULL , 
     description VARCHAR2 (250) , 
     base_price NUMBER (9,2)  NOT NULL , 
     floorplan_links VARCHAR2 (250) 
    ) 
;



ALTER TABLE Style_code_table 
    ADD CONSTRAINT Style_code_table_PK PRIMARY KEY ( style_id ) ;



CREATE TABLE Style_elevation 
    ( 
     style_elevation_id NUMBER  NOT NULL , 
     elevation_id NUMBER  NOT NULL , 
     style_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Style_elevation 
    ADD CONSTRAINT Style_elevation_PK PRIMARY KEY ( style_elevation_id ) ;



CREATE TABLE Subdivision 
    ( 
     subdivision_id NUMBER  NOT NULL , 
     school_district_id NUMBER  NOT NULL , 
     name VARCHAR2 (25)  NOT NULL , 
     map BLOB , 
     city VARCHAR2 (25)  NOT NULL , 
     state VARCHAR2 (2)  NOT NULL CHECK ( state IN ('AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY')) , 
     zipcode VARCHAR2 (10)  NOT NULL 
    ) 
;



ALTER TABLE Subdivision 
    ADD CONSTRAINT Subdivision_PK PRIMARY KEY ( subdivision_id ) ;



CREATE TABLE Subdivision_agreement 
    ( 
     subdivision_agreement_id NUMBER  NOT NULL , 
     subdivision_id NUMBER  NOT NULL , 
     start_date DATE  NOT NULL , 
     end_date DATE , 
     description VARCHAR2 (250) 
    ) 
;



ALTER TABLE Subdivision_agreement 
    ADD CONSTRAINT Subdivision_agreement_PK PRIMARY KEY ( subdivision_agreement_id ) ;



CREATE TABLE Subdivision_style_option 
    ( 
     subdivision_style_option_id NUMBER  NOT NULL , 
     subdivision_id NUMBER  NOT NULL , 
     style_id NUMBER  NOT NULL 
    ) 
;



ALTER TABLE Subdivision_style_option 
    ADD CONSTRAINT Subdivision_style_option_PK PRIMARY KEY ( subdivision_style_option_id ) ;



CREATE TABLE Task 
    ( 
     task_id NUMBER  NOT NULL , 
     name VARCHAR2 (25)  NOT NULL , 
     description VARCHAR2 (250) , 
     stage_selected_option_id NUMBER 
    ) 
;



ALTER TABLE Task 
    ADD CONSTRAINT Task_PK PRIMARY KEY ( task_id ) ;



CREATE TABLE Task_update 
    ( 
     task_update_id NUMBER  NOT NULL , 
     task_id NUMBER  NOT NULL , 
     employee_id NUMBER  NOT NULL , 
     construction_project_id NUMBER  NOT NULL , 
     "date" DATE  NOT NULL , 
     percent_complete NUMBER (5,2)  NOT NULL , 
     notes VARCHAR2 (250)  NOT NULL , 
     photo BLOB 
    ) 
;



ALTER TABLE Task_update 
    ADD CONSTRAINT Update_PK PRIMARY KEY ( task_update_id ) ;




ALTER TABLE Constr_worker_crew_assign 
    ADD CONSTRAINT Crew_constr_worker_assign_rel FOREIGN KEY 
    ( 
     crew_id
    ) 
    REFERENCES Crew 
    ( 
     crew_id
    ) 
;


ALTER TABLE Crew_project_assignment 
    ADD CONSTRAINT Crew_construction_project_rel FOREIGN KEY 
    ( 
     construction_project_id
    ) 
    REFERENCES Construction_project 
    ( 
     construction_project_id
    ) 
;


ALTER TABLE Crew_project_assignment 
    ADD CONSTRAINT Crew_crew_assignment_rel FOREIGN KEY 
    ( 
     crew_id
    ) 
    REFERENCES Crew 
    ( 
     crew_id
    ) 
;


ALTER TABLE Contract 
    ADD CONSTRAINT Disclosure_contract_rel FOREIGN KEY 
    ( 
     disclosure_form_id
    ) 
    REFERENCES Disclosure_form 
    ( 
     disclosure_form_id
    ) 
;


ALTER TABLE Employee 
    ADD CONSTRAINT Employee_user_rel FOREIGN KEY 
    ( 
     app_user_id
    ) 
    REFERENCES App_User 
    ( 
     app_user_id
    ) 
;


ALTER TABLE Construction_project 
    ADD CONSTRAINT House_construction_project_rel FOREIGN KEY 
    ( 
     house_id
    ) 
    REFERENCES House 
    ( 
     house_id
    ) 
;


ALTER TABLE House 
    ADD CONSTRAINT House_lot_rel FOREIGN KEY 
    ( 
     lot_id
    ) 
    REFERENCES Lot 
    ( 
     lot_id
    ) 
;


ALTER TABLE Lot 
    ADD CONSTRAINT Lot_style_elevation FOREIGN KEY 
    ( 
     style_elevation_id
    ) 
    REFERENCES Style_elevation 
    ( 
     style_elevation_id
    ) 
;


ALTER TABLE Style_elevation 
    ADD CONSTRAINT Style_elevation_rel FOREIGN KEY 
    ( 
     elevation_id
    ) 
    REFERENCES Elevation_code_table 
    ( 
     elevation_id
    ) 
;


ALTER TABLE Style_elevation 
    ADD CONSTRAINT Style_style_elevation_rel FOREIGN KEY 
    ( 
     style_id
    ) 
    REFERENCES Style_code_table 
    ( 
     style_id
    ) 
;


ALTER TABLE Contract 
    ADD CONSTRAINT Subdiv_agreement_contract FOREIGN KEY 
    ( 
     subdivision_agreement_id
    ) 
    REFERENCES Subdivision_agreement 
    ( 
     subdivision_agreement_id
    ) 
;


ALTER TABLE Lot 
    ADD CONSTRAINT Subdivision_lot_rel FOREIGN KEY 
    ( 
     subdivision_id
    ) 
    REFERENCES Subdivision 
    ( 
     subdivision_id
    ) 
;


ALTER TABLE Constr_worker_crew_assign 
    ADD CONSTRAINT const_worker_crew_assign_rel FOREIGN KEY 
    ( 
     construction_worker_id
    ) 
    REFERENCES Construction_worker 
    ( 
     construction_worker_id
    ) 
;


ALTER TABLE Construction_project 
    ADD CONSTRAINT constr_project_manager_rel FOREIGN KEY 
    ( 
     project_manager_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id
    ) 
;


ALTER TABLE Stage_assignment 
    ADD CONSTRAINT construction_project_stage FOREIGN KEY 
    ( 
     construction_project_id
    ) 
    REFERENCES Construction_project 
    ( 
     construction_project_id
    ) 
;


ALTER TABLE Task_update 
    ADD CONSTRAINT construction_project_update FOREIGN KEY 
    ( 
     construction_project_id
    ) 
    REFERENCES Construction_project 
    ( 
     construction_project_id
    ) 
;


ALTER TABLE Customer_contract_assign 
    ADD CONSTRAINT contract_customer_rel FOREIGN KEY 
    ( 
     contract_id
    ) 
    REFERENCES Contract 
    ( 
     contract_id
    ) 
;


ALTER TABLE Sale 
    ADD CONSTRAINT contract_sales_agent FOREIGN KEY 
    ( 
     sales_agent_id
    ) 
    REFERENCES Sales_agent 
    ( 
     sales_agent_id
    ) 
;


ALTER TABLE Crew 
    ADD CONSTRAINT crew_manager FOREIGN KEY 
    ( 
     manager_id
    ) 
    REFERENCES Construction_worker 
    ( 
     construction_worker_id
    ) 
;


ALTER TABLE Customer_contract_assign 
    ADD CONSTRAINT customer_contract_rel FOREIGN KEY 
    ( 
     customer_id
    ) 
    REFERENCES Customer 
    ( 
     customer_id
    ) 
;


ALTER TABLE Customer 
    ADD CONSTRAINT customer_user FOREIGN KEY 
    ( 
     app_user_id
    ) 
    REFERENCES App_User 
    ( 
     app_user_id
    ) 
;


ALTER TABLE Construction_worker 
    ADD CONSTRAINT employee_consty_worker_rel FOREIGN KEY 
    ( 
     employee_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id
    ) 
;


ALTER TABLE Task_update 
    ADD CONSTRAINT employee_update FOREIGN KEY 
    ( 
     employee_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id
    ) 
;


ALTER TABLE Floor 
    ADD CONSTRAINT floor_assignment FOREIGN KEY 
    ( 
     house_id
    ) 
    REFERENCES House 
    ( 
     house_id
    ) 
;


ALTER TABLE Room_assignment 
    ADD CONSTRAINT floor_room_rel FOREIGN KEY 
    ( 
     floor_id
    ) 
    REFERENCES Floor 
    ( 
     floor_id
    ) 
;


ALTER TABLE House 
    ADD CONSTRAINT house_house_style_rel FOREIGN KEY 
    ( 
     house_style_id
    ) 
    REFERENCES House_style 
    ( 
     house_style_id
    ) 
;


ALTER TABLE Sale 
    ADD CONSTRAINT house_sale FOREIGN KEY 
    ( 
     house_id
    ) 
    REFERENCES House 
    ( 
     house_id
    ) 
;


ALTER TABLE Sales_agent_assignment 
    ADD CONSTRAINT house_sales_agent_assign_rel FOREIGN KEY 
    ( 
     house_id
    ) 
    REFERENCES House 
    ( 
     house_id
    ) 
;


ALTER TABLE Stage_selected_option 
    ADD CONSTRAINT house_stage_selected_opt_rel FOREIGN KEY 
    ( 
     construction_project_id
    ) 
    REFERENCES Construction_project 
    ( 
     construction_project_id
    ) 
;


ALTER TABLE Option_code_table 
    ADD CONSTRAINT last_possible_stage_rel FOREIGN KEY 
    ( 
     last_possible_stage
    ) 
    REFERENCES Stage_code_table 
    ( 
     stage_id
    ) 
;


ALTER TABLE House_style 
    ADD CONSTRAINT reversed_style FOREIGN KEY 
    ( 
     reversed_style_id
    ) 
    REFERENCES House_style 
    ( 
     house_style_id
    ) 
;


ALTER TABLE Room_assignment 
    ADD CONSTRAINT room_room_assignment_rel FOREIGN KEY 
    ( 
     room_id
    ) 
    REFERENCES Room 
    ( 
     room_id
    ) 
;


ALTER TABLE Sales_agent_assignment 
    ADD CONSTRAINT sales_agent_assignment_rel FOREIGN KEY 
    ( 
     sales_agent_id
    ) 
    REFERENCES Sales_agent 
    ( 
     sales_agent_id
    ) 
;


ALTER TABLE Sales_agent 
    ADD CONSTRAINT sales_agent_employee_rel FOREIGN KEY 
    ( 
     employee_id
    ) 
    REFERENCES Employee 
    ( 
     employee_id
    ) 
;


ALTER TABLE School 
    ADD CONSTRAINT school_district_school_rel FOREIGN KEY 
    ( 
     school_district_id
    ) 
    REFERENCES School_district 
    ( 
     school_district_id
    ) 
;


ALTER TABLE Option_for_stage 
    ADD CONSTRAINT stage_option_for_stage_rel FOREIGN KEY 
    ( 
     stage_id
    ) 
    REFERENCES Stage_code_table 
    ( 
     stage_id
    ) 
;


ALTER TABLE Option_for_stage 
    ADD CONSTRAINT stage_option_rel FOREIGN KEY 
    ( 
     option_id
    ) 
    REFERENCES Option_code_table 
    ( 
     option_id
    ) 
;


ALTER TABLE Stage_selected_option 
    ADD CONSTRAINT stage_selected_option_room_rel FOREIGN KEY 
    ( 
     room_assignment_id
    ) 
    REFERENCES Room_assignment 
    ( 
     room_assignment_id
    ) 
;


ALTER TABLE Stage_assignment 
    ADD CONSTRAINT stage_stage_assignment_rel FOREIGN KEY 
    ( 
     stage_id
    ) 
    REFERENCES Stage_code_table 
    ( 
     stage_id
    ) 
;


ALTER TABLE Stage_selected_option 
    ADD CONSTRAINT stage_stage_option FOREIGN KEY 
    ( 
     option_for_stage_id
    ) 
    REFERENCES Option_for_stage 
    ( 
     option_for_stage_id
    ) 
;


ALTER TABLE Subdivision_style_option 
    ADD CONSTRAINT style_for_subdivision_rel FOREIGN KEY 
    ( 
     style_id
    ) 
    REFERENCES Style_code_table 
    ( 
     style_id
    ) 
;


ALTER TABLE Subdivision_agreement 
    ADD CONSTRAINT subdiv_agreement_rel FOREIGN KEY 
    ( 
     subdivision_id
    ) 
    REFERENCES Subdivision 
    ( 
     subdivision_id
    ) 
;


ALTER TABLE Subdivision 
    ADD CONSTRAINT subdiv_school_district_rel FOREIGN KEY 
    ( 
     school_district_id
    ) 
    REFERENCES School_district 
    ( 
     school_district_id
    ) 
;


ALTER TABLE Subdivision_style_option 
    ADD CONSTRAINT subdivision_style_rel FOREIGN KEY 
    ( 
     subdivision_id
    ) 
    REFERENCES Subdivision 
    ( 
     subdivision_id
    ) 
;


ALTER TABLE Task 
    ADD CONSTRAINT task_stage_option_rel FOREIGN KEY 
    ( 
     stage_selected_option_id
    ) 
    REFERENCES Stage_selected_option 
    ( 
     stage_selected_option_id
    ) 
;


ALTER TABLE Task_update 
    ADD CONSTRAINT task_update_rel FOREIGN KEY 
    ( 
     task_id
    ) 
    REFERENCES Task 
    ( 
     task_id
    ) 
;

